/* AutoGenerated Code, changes may be overwritten
 * INPUT GRAMMAR:
 * mailbox         :=    name_addr | addr_spec
 * name_addr       :=    display_name? angle_addr
 * addr_spec       :=    local_part '@' domain
 * display_name    :=    phrase
 * angle_addr      :=    CFWS? '<' addr_spec '>' CFWS? | obs_angle_addr
 * local_part      :=    dot_atom | quoted_string | obs_local_part
 * domain          :=    dot_atom | domain_literal | obs_domain
 * phrase          :=    word+ | obs_phrase
 * CFWS            :=    { FWS? comment }+ FWS? | FWS
 * obs_angle_addr  :=    CFWS? '<' obs_route addr_spec '>' CFWS?
 * dot_atom        :=    CFWS? dot_atom_text CFWS?
 * quoted_string   :=    CFWS? DQUOTE { FWS? qcontent }* FWS? DQUOTE CFWS?
 * obs_local_part  :=    word { '\.' word }*
 * domain_literal  :=    CFWS? '\[' { FWS? dtext }* FWS? '\]' CFWS?
 * obs_domain      :=    atom { '\.' atom }*
 * word            :=    atom | quoted_string
 * obs_phrase      :=    word { word | '.' | CFWS }
 * FWS             :=    { WSP* CRLF }? WSP+ |  obs_FWS
 * comment         :=    '\(' { FWS? ccontent }* FWS? '\)'
 * obs_route       :=    obs_domain_list ':'
 * dot_atom_text   :=    atext+ { '\.' atext+ }*
 * DQUOTE          :=    '\x22'              // double quote, i.e. '"'
 * qcontent        :=    qtext | quoted_pair
 * dtext           :=    '[\x21-\x5a]' | '[\x5e-\x7e]' | obs_dtext
 * atom            :=    CFWS? atext+ CFWS?
 * WSP             :=    SP | HTAB           // white space
 * obs_FWS         :=    WSP+ { CRLF WSP+ }*
 * CRLF            :=    '\r\n'              // Internet standard newline
 * ccontent        :=    ctext | quoted_pair | comment
 * obs_domain_list :=    { CFWS | ',' }* '@' domain { ',' CFWS? { '@' domain }? }*
 * atext           :=    '[A-Za-z0-9!#$%&\x27\*\+\-\/=?^_`{|}~]'
 * qtext           :=    '\x21' | '[\x23-\x5b]' | '[\x5d-\x7e]' | obs_qtext
 * quoted_pair     :=    '\\' { VCHAR | WSP }  | obs_qp
 * obs_dtext       :=    obs_NO_WS_CTL | quoted_pair
 * SP              :=    '\x20'              // space, i.e. 'Space'
 * HTAB            :=    '\x09'              // horizontal tab, i.e. 'TAB'
 * ctext           :=    '[\x21-\x27]' | '[\x2a-\x5b]' | '[\x5d-\x7e]' | obs_ctext
 * obs_qtext       :=    obs_NO_WS_CTL
 * obs_qp          :=    '\\' { '\x00' | obs_NO_WS_CTL | LF | CR }
 * VCHAR           :=    '[\x21-\x7E]'       // visible (printing) characters
 * obs_NO_WS_CTL   :=    '[\x01-\x08]' | '\x0B' | '\x0C' | '[\x0E-\x1F]' | '\x7F'
 * obs_ctext       :=    obs_NO_WS_CTL
 * LF              :=    '\x0A'              // linefeed, i.e. '\n'
 * CR              :=    '\x0D'              // carriage return, i.e. '\r'
 */
type Nullable<T> = T | null
type $$RuleType<T> = () => Nullable<T>
export interface ASTNodeIntf {
  kind: ASTKinds
}
export enum ASTKinds {
  mailbox_1 = 'mailbox_1',
  mailbox_2 = 'mailbox_2',
  name_addr = 'name_addr',
  addr_spec = 'addr_spec',
  display_name = 'display_name',
  angle_addr_1 = 'angle_addr_1',
  angle_addr_2 = 'angle_addr_2',
  local_part_1 = 'local_part_1',
  local_part_2 = 'local_part_2',
  local_part_3 = 'local_part_3',
  domain_1 = 'domain_1',
  domain_2 = 'domain_2',
  domain_3 = 'domain_3',
  phrase_1 = 'phrase_1',
  phrase_2 = 'phrase_2',
  CFWS_1 = 'CFWS_1',
  CFWS_2 = 'CFWS_2',
  CFWS_$0 = 'CFWS_$0',
  obs_angle_addr = 'obs_angle_addr',
  dot_atom = 'dot_atom',
  quoted_string = 'quoted_string',
  quoted_string_$0 = 'quoted_string_$0',
  obs_local_part = 'obs_local_part',
  obs_local_part_$0 = 'obs_local_part_$0',
  domain_literal = 'domain_literal',
  domain_literal_$0 = 'domain_literal_$0',
  obs_domain = 'obs_domain',
  obs_domain_$0 = 'obs_domain_$0',
  word_1 = 'word_1',
  word_2 = 'word_2',
  obs_phrase = 'obs_phrase',
  obs_phrase_$0_1 = 'obs_phrase_$0_1',
  obs_phrase_$0_2 = 'obs_phrase_$0_2',
  obs_phrase_$0_3 = 'obs_phrase_$0_3',
  FWS_1 = 'FWS_1',
  FWS_2 = 'FWS_2',
  FWS_$0 = 'FWS_$0',
  comment = 'comment',
  comment_$0 = 'comment_$0',
  obs_route = 'obs_route',
  dot_atom_text = 'dot_atom_text',
  dot_atom_text_$0 = 'dot_atom_text_$0',
  DQUOTE = 'DQUOTE',
  qcontent_1 = 'qcontent_1',
  qcontent_2 = 'qcontent_2',
  dtext_1 = 'dtext_1',
  dtext_2 = 'dtext_2',
  dtext_3 = 'dtext_3',
  atom = 'atom',
  WSP_1 = 'WSP_1',
  WSP_2 = 'WSP_2',
  obs_FWS = 'obs_FWS',
  obs_FWS_$0 = 'obs_FWS_$0',
  CRLF = 'CRLF',
  ccontent_1 = 'ccontent_1',
  ccontent_2 = 'ccontent_2',
  ccontent_3 = 'ccontent_3',
  obs_domain_list = 'obs_domain_list',
  obs_domain_list_$0_1 = 'obs_domain_list_$0_1',
  obs_domain_list_$0_2 = 'obs_domain_list_$0_2',
  obs_domain_list_$1 = 'obs_domain_list_$1',
  obs_domain_list_$1_$0 = 'obs_domain_list_$1_$0',
  atext = 'atext',
  qtext_1 = 'qtext_1',
  qtext_2 = 'qtext_2',
  qtext_3 = 'qtext_3',
  qtext_4 = 'qtext_4',
  quoted_pair_1 = 'quoted_pair_1',
  quoted_pair_2 = 'quoted_pair_2',
  quoted_pair_$0_1 = 'quoted_pair_$0_1',
  quoted_pair_$0_2 = 'quoted_pair_$0_2',
  obs_dtext_1 = 'obs_dtext_1',
  obs_dtext_2 = 'obs_dtext_2',
  SP = 'SP',
  HTAB = 'HTAB',
  ctext_1 = 'ctext_1',
  ctext_2 = 'ctext_2',
  ctext_3 = 'ctext_3',
  ctext_4 = 'ctext_4',
  obs_qtext = 'obs_qtext',
  obs_qp = 'obs_qp',
  obs_qp_$0_1 = 'obs_qp_$0_1',
  obs_qp_$0_2 = 'obs_qp_$0_2',
  obs_qp_$0_3 = 'obs_qp_$0_3',
  obs_qp_$0_4 = 'obs_qp_$0_4',
  VCHAR = 'VCHAR',
  obs_NO_WS_CTL_1 = 'obs_NO_WS_CTL_1',
  obs_NO_WS_CTL_2 = 'obs_NO_WS_CTL_2',
  obs_NO_WS_CTL_3 = 'obs_NO_WS_CTL_3',
  obs_NO_WS_CTL_4 = 'obs_NO_WS_CTL_4',
  obs_NO_WS_CTL_5 = 'obs_NO_WS_CTL_5',
  obs_ctext = 'obs_ctext',
  LF = 'LF',
  CR = 'CR',
}
export type mailbox = mailbox_1 | mailbox_2
export type mailbox_1 = name_addr
export type mailbox_2 = addr_spec
export interface name_addr {
  kind: ASTKinds.name_addr
}
export interface addr_spec {
  kind: ASTKinds.addr_spec
}
export type display_name = phrase
export type angle_addr = angle_addr_1 | angle_addr_2
export interface angle_addr_1 {
  kind: ASTKinds.angle_addr_1
}
export type angle_addr_2 = obs_angle_addr
export type local_part = local_part_1 | local_part_2 | local_part_3
export type local_part_1 = dot_atom
export type local_part_2 = quoted_string
export type local_part_3 = obs_local_part
export type domain = domain_1 | domain_2 | domain_3
export type domain_1 = dot_atom
export type domain_2 = domain_literal
export type domain_3 = obs_domain
export type phrase = phrase_1 | phrase_2
export type phrase_1 = [word, ...word[]]
export type phrase_2 = obs_phrase
export type CFWS = CFWS_1 | CFWS_2
export interface CFWS_1 {
  kind: ASTKinds.CFWS_1
}
export type CFWS_2 = FWS
export interface CFWS_$0 {
  kind: ASTKinds.CFWS_$0
}
export interface obs_angle_addr {
  kind: ASTKinds.obs_angle_addr
}
export interface dot_atom {
  kind: ASTKinds.dot_atom
}
export interface quoted_string {
  kind: ASTKinds.quoted_string
}
export interface quoted_string_$0 {
  kind: ASTKinds.quoted_string_$0
}
export interface obs_local_part {
  kind: ASTKinds.obs_local_part
}
export interface obs_local_part_$0 {
  kind: ASTKinds.obs_local_part_$0
}
export interface domain_literal {
  kind: ASTKinds.domain_literal
}
export interface domain_literal_$0 {
  kind: ASTKinds.domain_literal_$0
}
export interface obs_domain {
  kind: ASTKinds.obs_domain
}
export interface obs_domain_$0 {
  kind: ASTKinds.obs_domain_$0
}
export type word = word_1 | word_2
export type word_1 = atom
export type word_2 = quoted_string
export interface obs_phrase {
  kind: ASTKinds.obs_phrase
}
export type obs_phrase_$0 = obs_phrase_$0_1 | obs_phrase_$0_2 | obs_phrase_$0_3
export type obs_phrase_$0_1 = word
export type obs_phrase_$0_2 = string
export type obs_phrase_$0_3 = CFWS
export type FWS = FWS_1 | FWS_2
export interface FWS_1 {
  kind: ASTKinds.FWS_1
}
export type FWS_2 = obs_FWS
export interface FWS_$0 {
  kind: ASTKinds.FWS_$0
}
export interface comment {
  kind: ASTKinds.comment
}
export interface comment_$0 {
  kind: ASTKinds.comment_$0
}
export interface obs_route {
  kind: ASTKinds.obs_route
}
export interface dot_atom_text {
  kind: ASTKinds.dot_atom_text
}
export interface dot_atom_text_$0 {
  kind: ASTKinds.dot_atom_text_$0
}
export type DQUOTE = string
export type qcontent = qcontent_1 | qcontent_2
export type qcontent_1 = qtext
export type qcontent_2 = quoted_pair
export type dtext = dtext_1 | dtext_2 | dtext_3
export type dtext_1 = string
export type dtext_2 = string
export type dtext_3 = obs_dtext
export interface atom {
  kind: ASTKinds.atom
}
export type WSP = WSP_1 | WSP_2
export type WSP_1 = SP
export type WSP_2 = HTAB
export interface obs_FWS {
  kind: ASTKinds.obs_FWS
}
export interface obs_FWS_$0 {
  kind: ASTKinds.obs_FWS_$0
}
export type CRLF = string
export type ccontent = ccontent_1 | ccontent_2 | ccontent_3
export type ccontent_1 = ctext
export type ccontent_2 = quoted_pair
export type ccontent_3 = comment
export interface obs_domain_list {
  kind: ASTKinds.obs_domain_list
}
export type obs_domain_list_$0 = obs_domain_list_$0_1 | obs_domain_list_$0_2
export type obs_domain_list_$0_1 = CFWS
export type obs_domain_list_$0_2 = string
export interface obs_domain_list_$1 {
  kind: ASTKinds.obs_domain_list_$1
}
export interface obs_domain_list_$1_$0 {
  kind: ASTKinds.obs_domain_list_$1_$0
}
export type atext = string
export type qtext = qtext_1 | qtext_2 | qtext_3 | qtext_4
export type qtext_1 = string
export type qtext_2 = string
export type qtext_3 = string
export type qtext_4 = obs_qtext
export type quoted_pair = quoted_pair_1 | quoted_pair_2
export interface quoted_pair_1 {
  kind: ASTKinds.quoted_pair_1
}
export type quoted_pair_2 = obs_qp
export type quoted_pair_$0 = quoted_pair_$0_1 | quoted_pair_$0_2
export type quoted_pair_$0_1 = VCHAR
export type quoted_pair_$0_2 = WSP
export type obs_dtext = obs_dtext_1 | obs_dtext_2
export type obs_dtext_1 = obs_NO_WS_CTL
export type obs_dtext_2 = quoted_pair
export type SP = string
export type HTAB = string
export type ctext = ctext_1 | ctext_2 | ctext_3 | ctext_4
export type ctext_1 = string
export type ctext_2 = string
export type ctext_3 = string
export type ctext_4 = obs_ctext
export type obs_qtext = obs_NO_WS_CTL
export interface obs_qp {
  kind: ASTKinds.obs_qp
}
export type obs_qp_$0 = obs_qp_$0_1 | obs_qp_$0_2 | obs_qp_$0_3 | obs_qp_$0_4
export type obs_qp_$0_1 = string
export type obs_qp_$0_2 = obs_NO_WS_CTL
export type obs_qp_$0_3 = LF
export type obs_qp_$0_4 = CR
export type VCHAR = string
export type obs_NO_WS_CTL =
  | obs_NO_WS_CTL_1
  | obs_NO_WS_CTL_2
  | obs_NO_WS_CTL_3
  | obs_NO_WS_CTL_4
  | obs_NO_WS_CTL_5
export type obs_NO_WS_CTL_1 = string
export type obs_NO_WS_CTL_2 = string
export type obs_NO_WS_CTL_3 = string
export type obs_NO_WS_CTL_4 = string
export type obs_NO_WS_CTL_5 = string
export type obs_ctext = obs_NO_WS_CTL
export type LF = string
export type CR = string
export class Parser {
  private readonly input: string
  private pos: PosInfo
  private negating: boolean = false
  private memoSafe: boolean = true
  constructor(input: string) {
    this.pos = { overallPos: 0, line: 1, offset: 0 }
    this.input = input
  }
  public reset(pos: PosInfo) {
    this.pos = pos
  }
  public finished(): boolean {
    return this.pos.overallPos === this.input.length
  }
  public clearMemos(): void {}
  public matchmailbox($$dpth: number, $$cr?: ErrorTracker): Nullable<mailbox> {
    return this.choice<mailbox>([
      () => this.matchmailbox_1($$dpth + 1, $$cr),
      () => this.matchmailbox_2($$dpth + 1, $$cr),
    ])
  }
  public matchmailbox_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<mailbox_1> {
    return this.matchname_addr($$dpth + 1, $$cr)
  }
  public matchmailbox_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<mailbox_2> {
    return this.matchaddr_spec($$dpth + 1, $$cr)
  }
  public matchname_addr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<name_addr> {
    return this.run<name_addr>($$dpth, () => {
      let $$res: Nullable<name_addr> = null
      if (
        true &&
        (this.matchdisplay_name($$dpth + 1, $$cr) || true) &&
        this.matchangle_addr($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.name_addr }
      }
      return $$res
    })
  }
  public matchaddr_spec(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<addr_spec> {
    return this.run<addr_spec>($$dpth, () => {
      let $$res: Nullable<addr_spec> = null
      if (
        true &&
        this.matchlocal_part($$dpth + 1, $$cr) !== null &&
        this.regexAccept(String.raw`(?:@)`, '', $$dpth + 1, $$cr) !== null &&
        this.matchdomain($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.addr_spec }
      }
      return $$res
    })
  }
  public matchdisplay_name(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<display_name> {
    return this.matchphrase($$dpth + 1, $$cr)
  }
  public matchangle_addr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<angle_addr> {
    return this.choice<angle_addr>([
      () => this.matchangle_addr_1($$dpth + 1, $$cr),
      () => this.matchangle_addr_2($$dpth + 1, $$cr),
    ])
  }
  public matchangle_addr_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<angle_addr_1> {
    return this.run<angle_addr_1>($$dpth, () => {
      let $$res: Nullable<angle_addr_1> = null
      if (
        true &&
        (this.matchCFWS($$dpth + 1, $$cr) || true) &&
        this.regexAccept(String.raw`(?:<)`, '', $$dpth + 1, $$cr) !== null &&
        this.matchaddr_spec($$dpth + 1, $$cr) !== null &&
        this.regexAccept(String.raw`(?:>)`, '', $$dpth + 1, $$cr) !== null &&
        (this.matchCFWS($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.angle_addr_1 }
      }
      return $$res
    })
  }
  public matchangle_addr_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<angle_addr_2> {
    return this.matchobs_angle_addr($$dpth + 1, $$cr)
  }
  public matchlocal_part(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<local_part> {
    return this.choice<local_part>([
      () => this.matchlocal_part_1($$dpth + 1, $$cr),
      () => this.matchlocal_part_2($$dpth + 1, $$cr),
      () => this.matchlocal_part_3($$dpth + 1, $$cr),
    ])
  }
  public matchlocal_part_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<local_part_1> {
    return this.matchdot_atom($$dpth + 1, $$cr)
  }
  public matchlocal_part_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<local_part_2> {
    return this.matchquoted_string($$dpth + 1, $$cr)
  }
  public matchlocal_part_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<local_part_3> {
    return this.matchobs_local_part($$dpth + 1, $$cr)
  }
  public matchdomain($$dpth: number, $$cr?: ErrorTracker): Nullable<domain> {
    return this.choice<domain>([
      () => this.matchdomain_1($$dpth + 1, $$cr),
      () => this.matchdomain_2($$dpth + 1, $$cr),
      () => this.matchdomain_3($$dpth + 1, $$cr),
    ])
  }
  public matchdomain_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<domain_1> {
    return this.matchdot_atom($$dpth + 1, $$cr)
  }
  public matchdomain_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<domain_2> {
    return this.matchdomain_literal($$dpth + 1, $$cr)
  }
  public matchdomain_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<domain_3> {
    return this.matchobs_domain($$dpth + 1, $$cr)
  }
  public matchphrase($$dpth: number, $$cr?: ErrorTracker): Nullable<phrase> {
    return this.choice<phrase>([
      () => this.matchphrase_1($$dpth + 1, $$cr),
      () => this.matchphrase_2($$dpth + 1, $$cr),
    ])
  }
  public matchphrase_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<phrase_1> {
    return this.loopPlus<word>(() => this.matchword($$dpth + 1, $$cr))
  }
  public matchphrase_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<phrase_2> {
    return this.matchobs_phrase($$dpth + 1, $$cr)
  }
  public matchCFWS($$dpth: number, $$cr?: ErrorTracker): Nullable<CFWS> {
    return this.choice<CFWS>([
      () => this.matchCFWS_1($$dpth + 1, $$cr),
      () => this.matchCFWS_2($$dpth + 1, $$cr),
    ])
  }
  public matchCFWS_1($$dpth: number, $$cr?: ErrorTracker): Nullable<CFWS_1> {
    return this.run<CFWS_1>($$dpth, () => {
      let $$res: Nullable<CFWS_1> = null
      if (
        true &&
        this.loopPlus<CFWS_$0>(() => this.matchCFWS_$0($$dpth + 1, $$cr)) !==
          null &&
        (this.matchFWS($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.CFWS_1 }
      }
      return $$res
    })
  }
  public matchCFWS_2($$dpth: number, $$cr?: ErrorTracker): Nullable<CFWS_2> {
    return this.matchFWS($$dpth + 1, $$cr)
  }
  public matchCFWS_$0($$dpth: number, $$cr?: ErrorTracker): Nullable<CFWS_$0> {
    return this.run<CFWS_$0>($$dpth, () => {
      let $$res: Nullable<CFWS_$0> = null
      if (
        true &&
        (this.matchFWS($$dpth + 1, $$cr) || true) &&
        this.matchcomment($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.CFWS_$0 }
      }
      return $$res
    })
  }
  public matchobs_angle_addr(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_angle_addr> {
    return this.run<obs_angle_addr>($$dpth, () => {
      let $$res: Nullable<obs_angle_addr> = null
      if (
        true &&
        (this.matchCFWS($$dpth + 1, $$cr) || true) &&
        this.regexAccept(String.raw`(?:<)`, '', $$dpth + 1, $$cr) !== null &&
        this.matchobs_route($$dpth + 1, $$cr) !== null &&
        this.matchaddr_spec($$dpth + 1, $$cr) !== null &&
        this.regexAccept(String.raw`(?:>)`, '', $$dpth + 1, $$cr) !== null &&
        (this.matchCFWS($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.obs_angle_addr }
      }
      return $$res
    })
  }
  public matchdot_atom(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<dot_atom> {
    return this.run<dot_atom>($$dpth, () => {
      let $$res: Nullable<dot_atom> = null
      if (
        true &&
        (this.matchCFWS($$dpth + 1, $$cr) || true) &&
        this.matchdot_atom_text($$dpth + 1, $$cr) !== null &&
        (this.matchCFWS($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.dot_atom }
      }
      return $$res
    })
  }
  public matchquoted_string(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<quoted_string> {
    return this.run<quoted_string>($$dpth, () => {
      let $$res: Nullable<quoted_string> = null
      if (
        true &&
        (this.matchCFWS($$dpth + 1, $$cr) || true) &&
        this.matchDQUOTE($$dpth + 1, $$cr) !== null &&
        this.loop<quoted_string_$0>(
          () => this.matchquoted_string_$0($$dpth + 1, $$cr),
          0,
          -1,
        ) !== null &&
        (this.matchFWS($$dpth + 1, $$cr) || true) &&
        this.matchDQUOTE($$dpth + 1, $$cr) !== null &&
        (this.matchCFWS($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.quoted_string }
      }
      return $$res
    })
  }
  public matchquoted_string_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<quoted_string_$0> {
    return this.run<quoted_string_$0>($$dpth, () => {
      let $$res: Nullable<quoted_string_$0> = null
      if (
        true &&
        (this.matchFWS($$dpth + 1, $$cr) || true) &&
        this.matchqcontent($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.quoted_string_$0 }
      }
      return $$res
    })
  }
  public matchobs_local_part(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_local_part> {
    return this.run<obs_local_part>($$dpth, () => {
      let $$res: Nullable<obs_local_part> = null
      if (
        true &&
        this.matchword($$dpth + 1, $$cr) !== null &&
        this.loop<obs_local_part_$0>(
          () => this.matchobs_local_part_$0($$dpth + 1, $$cr),
          0,
          -1,
        ) !== null
      ) {
        $$res = { kind: ASTKinds.obs_local_part }
      }
      return $$res
    })
  }
  public matchobs_local_part_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_local_part_$0> {
    return this.run<obs_local_part_$0>($$dpth, () => {
      let $$res: Nullable<obs_local_part_$0> = null
      if (
        true &&
        this.regexAccept(String.raw`(?:\.)`, '', $$dpth + 1, $$cr) !== null &&
        this.matchword($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.obs_local_part_$0 }
      }
      return $$res
    })
  }
  public matchdomain_literal(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<domain_literal> {
    return this.run<domain_literal>($$dpth, () => {
      let $$res: Nullable<domain_literal> = null
      if (
        true &&
        (this.matchCFWS($$dpth + 1, $$cr) || true) &&
        this.regexAccept(String.raw`(?:\[)`, '', $$dpth + 1, $$cr) !== null &&
        this.loop<domain_literal_$0>(
          () => this.matchdomain_literal_$0($$dpth + 1, $$cr),
          0,
          -1,
        ) !== null &&
        (this.matchFWS($$dpth + 1, $$cr) || true) &&
        this.regexAccept(String.raw`(?:\])`, '', $$dpth + 1, $$cr) !== null &&
        (this.matchCFWS($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.domain_literal }
      }
      return $$res
    })
  }
  public matchdomain_literal_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<domain_literal_$0> {
    return this.run<domain_literal_$0>($$dpth, () => {
      let $$res: Nullable<domain_literal_$0> = null
      if (
        true &&
        (this.matchFWS($$dpth + 1, $$cr) || true) &&
        this.matchdtext($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.domain_literal_$0 }
      }
      return $$res
    })
  }
  public matchobs_domain(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_domain> {
    return this.run<obs_domain>($$dpth, () => {
      let $$res: Nullable<obs_domain> = null
      if (
        true &&
        this.matchatom($$dpth + 1, $$cr) !== null &&
        this.loop<obs_domain_$0>(
          () => this.matchobs_domain_$0($$dpth + 1, $$cr),
          0,
          -1,
        ) !== null
      ) {
        $$res = { kind: ASTKinds.obs_domain }
      }
      return $$res
    })
  }
  public matchobs_domain_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_domain_$0> {
    return this.run<obs_domain_$0>($$dpth, () => {
      let $$res: Nullable<obs_domain_$0> = null
      if (
        true &&
        this.regexAccept(String.raw`(?:\.)`, '', $$dpth + 1, $$cr) !== null &&
        this.matchatom($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.obs_domain_$0 }
      }
      return $$res
    })
  }
  public matchword($$dpth: number, $$cr?: ErrorTracker): Nullable<word> {
    return this.choice<word>([
      () => this.matchword_1($$dpth + 1, $$cr),
      () => this.matchword_2($$dpth + 1, $$cr),
    ])
  }
  public matchword_1($$dpth: number, $$cr?: ErrorTracker): Nullable<word_1> {
    return this.matchatom($$dpth + 1, $$cr)
  }
  public matchword_2($$dpth: number, $$cr?: ErrorTracker): Nullable<word_2> {
    return this.matchquoted_string($$dpth + 1, $$cr)
  }
  public matchobs_phrase(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_phrase> {
    return this.run<obs_phrase>($$dpth, () => {
      let $$res: Nullable<obs_phrase> = null
      if (
        true &&
        this.matchword($$dpth + 1, $$cr) !== null &&
        this.matchobs_phrase_$0($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.obs_phrase }
      }
      return $$res
    })
  }
  public matchobs_phrase_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_phrase_$0> {
    return this.choice<obs_phrase_$0>([
      () => this.matchobs_phrase_$0_1($$dpth + 1, $$cr),
      () => this.matchobs_phrase_$0_2($$dpth + 1, $$cr),
      () => this.matchobs_phrase_$0_3($$dpth + 1, $$cr),
    ])
  }
  public matchobs_phrase_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_phrase_$0_1> {
    return this.matchword($$dpth + 1, $$cr)
  }
  public matchobs_phrase_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_phrase_$0_2> {
    return this.regexAccept(String.raw`(?:.)`, '', $$dpth + 1, $$cr)
  }
  public matchobs_phrase_$0_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_phrase_$0_3> {
    return this.matchCFWS($$dpth + 1, $$cr)
  }
  public matchFWS($$dpth: number, $$cr?: ErrorTracker): Nullable<FWS> {
    return this.choice<FWS>([
      () => this.matchFWS_1($$dpth + 1, $$cr),
      () => this.matchFWS_2($$dpth + 1, $$cr),
    ])
  }
  public matchFWS_1($$dpth: number, $$cr?: ErrorTracker): Nullable<FWS_1> {
    return this.run<FWS_1>($$dpth, () => {
      let $$res: Nullable<FWS_1> = null
      if (
        true &&
        (this.matchFWS_$0($$dpth + 1, $$cr) || true) &&
        this.loopPlus<WSP>(() => this.matchWSP($$dpth + 1, $$cr)) !== null
      ) {
        $$res = { kind: ASTKinds.FWS_1 }
      }
      return $$res
    })
  }
  public matchFWS_2($$dpth: number, $$cr?: ErrorTracker): Nullable<FWS_2> {
    return this.matchobs_FWS($$dpth + 1, $$cr)
  }
  public matchFWS_$0($$dpth: number, $$cr?: ErrorTracker): Nullable<FWS_$0> {
    return this.run<FWS_$0>($$dpth, () => {
      let $$res: Nullable<FWS_$0> = null
      if (
        true &&
        this.loop<WSP>(() => this.matchWSP($$dpth + 1, $$cr), 0, -1) !== null &&
        this.matchCRLF($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.FWS_$0 }
      }
      return $$res
    })
  }
  public matchcomment($$dpth: number, $$cr?: ErrorTracker): Nullable<comment> {
    return this.run<comment>($$dpth, () => {
      let $$res: Nullable<comment> = null
      if (
        true &&
        this.regexAccept(String.raw`(?:\()`, '', $$dpth + 1, $$cr) !== null &&
        this.loop<comment_$0>(
          () => this.matchcomment_$0($$dpth + 1, $$cr),
          0,
          -1,
        ) !== null &&
        (this.matchFWS($$dpth + 1, $$cr) || true) &&
        this.regexAccept(String.raw`(?:\))`, '', $$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.comment }
      }
      return $$res
    })
  }
  public matchcomment_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<comment_$0> {
    return this.run<comment_$0>($$dpth, () => {
      let $$res: Nullable<comment_$0> = null
      if (
        true &&
        (this.matchFWS($$dpth + 1, $$cr) || true) &&
        this.matchccontent($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.comment_$0 }
      }
      return $$res
    })
  }
  public matchobs_route(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_route> {
    return this.run<obs_route>($$dpth, () => {
      let $$res: Nullable<obs_route> = null
      if (
        true &&
        this.matchobs_domain_list($$dpth + 1, $$cr) !== null &&
        this.regexAccept(String.raw`(?::)`, '', $$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.obs_route }
      }
      return $$res
    })
  }
  public matchdot_atom_text(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<dot_atom_text> {
    return this.run<dot_atom_text>($$dpth, () => {
      let $$res: Nullable<dot_atom_text> = null
      if (
        true &&
        this.loopPlus<atext>(() => this.matchatext($$dpth + 1, $$cr)) !==
          null &&
        this.loop<dot_atom_text_$0>(
          () => this.matchdot_atom_text_$0($$dpth + 1, $$cr),
          0,
          -1,
        ) !== null
      ) {
        $$res = { kind: ASTKinds.dot_atom_text }
      }
      return $$res
    })
  }
  public matchdot_atom_text_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<dot_atom_text_$0> {
    return this.run<dot_atom_text_$0>($$dpth, () => {
      let $$res: Nullable<dot_atom_text_$0> = null
      if (
        true &&
        this.regexAccept(String.raw`(?:\.)`, '', $$dpth + 1, $$cr) !== null &&
        this.loopPlus<atext>(() => this.matchatext($$dpth + 1, $$cr)) !== null
      ) {
        $$res = { kind: ASTKinds.dot_atom_text_$0 }
      }
      return $$res
    })
  }
  public matchDQUOTE($$dpth: number, $$cr?: ErrorTracker): Nullable<DQUOTE> {
    return this.regexAccept(String.raw`(?:\x22)`, '', $$dpth + 1, $$cr)
  }
  public matchqcontent(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<qcontent> {
    return this.choice<qcontent>([
      () => this.matchqcontent_1($$dpth + 1, $$cr),
      () => this.matchqcontent_2($$dpth + 1, $$cr),
    ])
  }
  public matchqcontent_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<qcontent_1> {
    return this.matchqtext($$dpth + 1, $$cr)
  }
  public matchqcontent_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<qcontent_2> {
    return this.matchquoted_pair($$dpth + 1, $$cr)
  }
  public matchdtext($$dpth: number, $$cr?: ErrorTracker): Nullable<dtext> {
    return this.choice<dtext>([
      () => this.matchdtext_1($$dpth + 1, $$cr),
      () => this.matchdtext_2($$dpth + 1, $$cr),
      () => this.matchdtext_3($$dpth + 1, $$cr),
    ])
  }
  public matchdtext_1($$dpth: number, $$cr?: ErrorTracker): Nullable<dtext_1> {
    return this.regexAccept(String.raw`(?:[\x21-\x5a])`, '', $$dpth + 1, $$cr)
  }
  public matchdtext_2($$dpth: number, $$cr?: ErrorTracker): Nullable<dtext_2> {
    return this.regexAccept(String.raw`(?:[\x5e-\x7e])`, '', $$dpth + 1, $$cr)
  }
  public matchdtext_3($$dpth: number, $$cr?: ErrorTracker): Nullable<dtext_3> {
    return this.matchobs_dtext($$dpth + 1, $$cr)
  }
  public matchatom($$dpth: number, $$cr?: ErrorTracker): Nullable<atom> {
    return this.run<atom>($$dpth, () => {
      let $$res: Nullable<atom> = null
      if (
        true &&
        (this.matchCFWS($$dpth + 1, $$cr) || true) &&
        this.loopPlus<atext>(() => this.matchatext($$dpth + 1, $$cr)) !==
          null &&
        (this.matchCFWS($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.atom }
      }
      return $$res
    })
  }
  public matchWSP($$dpth: number, $$cr?: ErrorTracker): Nullable<WSP> {
    return this.choice<WSP>([
      () => this.matchWSP_1($$dpth + 1, $$cr),
      () => this.matchWSP_2($$dpth + 1, $$cr),
    ])
  }
  public matchWSP_1($$dpth: number, $$cr?: ErrorTracker): Nullable<WSP_1> {
    return this.matchSP($$dpth + 1, $$cr)
  }
  public matchWSP_2($$dpth: number, $$cr?: ErrorTracker): Nullable<WSP_2> {
    return this.matchHTAB($$dpth + 1, $$cr)
  }
  public matchobs_FWS($$dpth: number, $$cr?: ErrorTracker): Nullable<obs_FWS> {
    return this.run<obs_FWS>($$dpth, () => {
      let $$res: Nullable<obs_FWS> = null
      if (
        true &&
        this.loopPlus<WSP>(() => this.matchWSP($$dpth + 1, $$cr)) !== null &&
        this.loop<obs_FWS_$0>(
          () => this.matchobs_FWS_$0($$dpth + 1, $$cr),
          0,
          -1,
        ) !== null
      ) {
        $$res = { kind: ASTKinds.obs_FWS }
      }
      return $$res
    })
  }
  public matchobs_FWS_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_FWS_$0> {
    return this.run<obs_FWS_$0>($$dpth, () => {
      let $$res: Nullable<obs_FWS_$0> = null
      if (
        true &&
        this.matchCRLF($$dpth + 1, $$cr) !== null &&
        this.loopPlus<WSP>(() => this.matchWSP($$dpth + 1, $$cr)) !== null
      ) {
        $$res = { kind: ASTKinds.obs_FWS_$0 }
      }
      return $$res
    })
  }
  public matchCRLF($$dpth: number, $$cr?: ErrorTracker): Nullable<CRLF> {
    return this.regexAccept(String.raw`(?:\r\n)`, '', $$dpth + 1, $$cr)
  }
  public matchccontent(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<ccontent> {
    return this.choice<ccontent>([
      () => this.matchccontent_1($$dpth + 1, $$cr),
      () => this.matchccontent_2($$dpth + 1, $$cr),
      () => this.matchccontent_3($$dpth + 1, $$cr),
    ])
  }
  public matchccontent_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<ccontent_1> {
    return this.matchctext($$dpth + 1, $$cr)
  }
  public matchccontent_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<ccontent_2> {
    return this.matchquoted_pair($$dpth + 1, $$cr)
  }
  public matchccontent_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<ccontent_3> {
    return this.matchcomment($$dpth + 1, $$cr)
  }
  public matchobs_domain_list(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_domain_list> {
    return this.run<obs_domain_list>($$dpth, () => {
      let $$res: Nullable<obs_domain_list> = null
      if (
        true &&
        this.loop<obs_domain_list_$0>(
          () => this.matchobs_domain_list_$0($$dpth + 1, $$cr),
          0,
          -1,
        ) !== null &&
        this.regexAccept(String.raw`(?:@)`, '', $$dpth + 1, $$cr) !== null &&
        this.matchdomain($$dpth + 1, $$cr) !== null &&
        this.loop<obs_domain_list_$1>(
          () => this.matchobs_domain_list_$1($$dpth + 1, $$cr),
          0,
          -1,
        ) !== null
      ) {
        $$res = { kind: ASTKinds.obs_domain_list }
      }
      return $$res
    })
  }
  public matchobs_domain_list_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_domain_list_$0> {
    return this.choice<obs_domain_list_$0>([
      () => this.matchobs_domain_list_$0_1($$dpth + 1, $$cr),
      () => this.matchobs_domain_list_$0_2($$dpth + 1, $$cr),
    ])
  }
  public matchobs_domain_list_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_domain_list_$0_1> {
    return this.matchCFWS($$dpth + 1, $$cr)
  }
  public matchobs_domain_list_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_domain_list_$0_2> {
    return this.regexAccept(String.raw`(?:,)`, '', $$dpth + 1, $$cr)
  }
  public matchobs_domain_list_$1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_domain_list_$1> {
    return this.run<obs_domain_list_$1>($$dpth, () => {
      let $$res: Nullable<obs_domain_list_$1> = null
      if (
        true &&
        this.regexAccept(String.raw`(?:,)`, '', $$dpth + 1, $$cr) !== null &&
        (this.matchCFWS($$dpth + 1, $$cr) || true) &&
        (this.matchobs_domain_list_$1_$0($$dpth + 1, $$cr) || true)
      ) {
        $$res = { kind: ASTKinds.obs_domain_list_$1 }
      }
      return $$res
    })
  }
  public matchobs_domain_list_$1_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_domain_list_$1_$0> {
    return this.run<obs_domain_list_$1_$0>($$dpth, () => {
      let $$res: Nullable<obs_domain_list_$1_$0> = null
      if (
        true &&
        this.regexAccept(String.raw`(?:@)`, '', $$dpth + 1, $$cr) !== null &&
        this.matchdomain($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.obs_domain_list_$1_$0 }
      }
      return $$res
    })
  }
  public matchatext($$dpth: number, $$cr?: ErrorTracker): Nullable<atext> {
    return this.regexAccept(
      String.raw`(?:[A-Za-z0-9!#$%&\x27\*\+\-\/=?^_\`{|}~])`,
      '',
      $$dpth + 1,
      $$cr,
    )
  }
  public matchqtext($$dpth: number, $$cr?: ErrorTracker): Nullable<qtext> {
    return this.choice<qtext>([
      () => this.matchqtext_1($$dpth + 1, $$cr),
      () => this.matchqtext_2($$dpth + 1, $$cr),
      () => this.matchqtext_3($$dpth + 1, $$cr),
      () => this.matchqtext_4($$dpth + 1, $$cr),
    ])
  }
  public matchqtext_1($$dpth: number, $$cr?: ErrorTracker): Nullable<qtext_1> {
    return this.regexAccept(String.raw`(?:\x21)`, '', $$dpth + 1, $$cr)
  }
  public matchqtext_2($$dpth: number, $$cr?: ErrorTracker): Nullable<qtext_2> {
    return this.regexAccept(String.raw`(?:[\x23-\x5b])`, '', $$dpth + 1, $$cr)
  }
  public matchqtext_3($$dpth: number, $$cr?: ErrorTracker): Nullable<qtext_3> {
    return this.regexAccept(String.raw`(?:[\x5d-\x7e])`, '', $$dpth + 1, $$cr)
  }
  public matchqtext_4($$dpth: number, $$cr?: ErrorTracker): Nullable<qtext_4> {
    return this.matchobs_qtext($$dpth + 1, $$cr)
  }
  public matchquoted_pair(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<quoted_pair> {
    return this.choice<quoted_pair>([
      () => this.matchquoted_pair_1($$dpth + 1, $$cr),
      () => this.matchquoted_pair_2($$dpth + 1, $$cr),
    ])
  }
  public matchquoted_pair_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<quoted_pair_1> {
    return this.run<quoted_pair_1>($$dpth, () => {
      let $$res: Nullable<quoted_pair_1> = null
      if (
        true &&
        this.regexAccept(String.raw`(?:\\)`, '', $$dpth + 1, $$cr) !== null &&
        this.matchquoted_pair_$0($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.quoted_pair_1 }
      }
      return $$res
    })
  }
  public matchquoted_pair_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<quoted_pair_2> {
    return this.matchobs_qp($$dpth + 1, $$cr)
  }
  public matchquoted_pair_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<quoted_pair_$0> {
    return this.choice<quoted_pair_$0>([
      () => this.matchquoted_pair_$0_1($$dpth + 1, $$cr),
      () => this.matchquoted_pair_$0_2($$dpth + 1, $$cr),
    ])
  }
  public matchquoted_pair_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<quoted_pair_$0_1> {
    return this.matchVCHAR($$dpth + 1, $$cr)
  }
  public matchquoted_pair_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<quoted_pair_$0_2> {
    return this.matchWSP($$dpth + 1, $$cr)
  }
  public matchobs_dtext(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_dtext> {
    return this.choice<obs_dtext>([
      () => this.matchobs_dtext_1($$dpth + 1, $$cr),
      () => this.matchobs_dtext_2($$dpth + 1, $$cr),
    ])
  }
  public matchobs_dtext_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_dtext_1> {
    return this.matchobs_NO_WS_CTL($$dpth + 1, $$cr)
  }
  public matchobs_dtext_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_dtext_2> {
    return this.matchquoted_pair($$dpth + 1, $$cr)
  }
  public matchSP($$dpth: number, $$cr?: ErrorTracker): Nullable<SP> {
    return this.regexAccept(String.raw`(?:\x20)`, '', $$dpth + 1, $$cr)
  }
  public matchHTAB($$dpth: number, $$cr?: ErrorTracker): Nullable<HTAB> {
    return this.regexAccept(String.raw`(?:\x09)`, '', $$dpth + 1, $$cr)
  }
  public matchctext($$dpth: number, $$cr?: ErrorTracker): Nullable<ctext> {
    return this.choice<ctext>([
      () => this.matchctext_1($$dpth + 1, $$cr),
      () => this.matchctext_2($$dpth + 1, $$cr),
      () => this.matchctext_3($$dpth + 1, $$cr),
      () => this.matchctext_4($$dpth + 1, $$cr),
    ])
  }
  public matchctext_1($$dpth: number, $$cr?: ErrorTracker): Nullable<ctext_1> {
    return this.regexAccept(String.raw`(?:[\x21-\x27])`, '', $$dpth + 1, $$cr)
  }
  public matchctext_2($$dpth: number, $$cr?: ErrorTracker): Nullable<ctext_2> {
    return this.regexAccept(String.raw`(?:[\x2a-\x5b])`, '', $$dpth + 1, $$cr)
  }
  public matchctext_3($$dpth: number, $$cr?: ErrorTracker): Nullable<ctext_3> {
    return this.regexAccept(String.raw`(?:[\x5d-\x7e])`, '', $$dpth + 1, $$cr)
  }
  public matchctext_4($$dpth: number, $$cr?: ErrorTracker): Nullable<ctext_4> {
    return this.matchobs_ctext($$dpth + 1, $$cr)
  }
  public matchobs_qtext(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_qtext> {
    return this.matchobs_NO_WS_CTL($$dpth + 1, $$cr)
  }
  public matchobs_qp($$dpth: number, $$cr?: ErrorTracker): Nullable<obs_qp> {
    return this.run<obs_qp>($$dpth, () => {
      let $$res: Nullable<obs_qp> = null
      if (
        true &&
        this.regexAccept(String.raw`(?:\\)`, '', $$dpth + 1, $$cr) !== null &&
        this.matchobs_qp_$0($$dpth + 1, $$cr) !== null
      ) {
        $$res = { kind: ASTKinds.obs_qp }
      }
      return $$res
    })
  }
  public matchobs_qp_$0(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_qp_$0> {
    return this.choice<obs_qp_$0>([
      () => this.matchobs_qp_$0_1($$dpth + 1, $$cr),
      () => this.matchobs_qp_$0_2($$dpth + 1, $$cr),
      () => this.matchobs_qp_$0_3($$dpth + 1, $$cr),
      () => this.matchobs_qp_$0_4($$dpth + 1, $$cr),
    ])
  }
  public matchobs_qp_$0_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_qp_$0_1> {
    return this.regexAccept(String.raw`(?:\x00)`, '', $$dpth + 1, $$cr)
  }
  public matchobs_qp_$0_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_qp_$0_2> {
    return this.matchobs_NO_WS_CTL($$dpth + 1, $$cr)
  }
  public matchobs_qp_$0_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_qp_$0_3> {
    return this.matchLF($$dpth + 1, $$cr)
  }
  public matchobs_qp_$0_4(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_qp_$0_4> {
    return this.matchCR($$dpth + 1, $$cr)
  }
  public matchVCHAR($$dpth: number, $$cr?: ErrorTracker): Nullable<VCHAR> {
    return this.regexAccept(String.raw`(?:[\x21-\x7E])`, '', $$dpth + 1, $$cr)
  }
  public matchobs_NO_WS_CTL(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_NO_WS_CTL> {
    return this.choice<obs_NO_WS_CTL>([
      () => this.matchobs_NO_WS_CTL_1($$dpth + 1, $$cr),
      () => this.matchobs_NO_WS_CTL_2($$dpth + 1, $$cr),
      () => this.matchobs_NO_WS_CTL_3($$dpth + 1, $$cr),
      () => this.matchobs_NO_WS_CTL_4($$dpth + 1, $$cr),
      () => this.matchobs_NO_WS_CTL_5($$dpth + 1, $$cr),
    ])
  }
  public matchobs_NO_WS_CTL_1(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_NO_WS_CTL_1> {
    return this.regexAccept(String.raw`(?:[\x01-\x08])`, '', $$dpth + 1, $$cr)
  }
  public matchobs_NO_WS_CTL_2(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_NO_WS_CTL_2> {
    return this.regexAccept(String.raw`(?:\x0B)`, '', $$dpth + 1, $$cr)
  }
  public matchobs_NO_WS_CTL_3(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_NO_WS_CTL_3> {
    return this.regexAccept(String.raw`(?:\x0C)`, '', $$dpth + 1, $$cr)
  }
  public matchobs_NO_WS_CTL_4(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_NO_WS_CTL_4> {
    return this.regexAccept(String.raw`(?:[\x0E-\x1F])`, '', $$dpth + 1, $$cr)
  }
  public matchobs_NO_WS_CTL_5(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_NO_WS_CTL_5> {
    return this.regexAccept(String.raw`(?:\x7F)`, '', $$dpth + 1, $$cr)
  }
  public matchobs_ctext(
    $$dpth: number,
    $$cr?: ErrorTracker,
  ): Nullable<obs_ctext> {
    return this.matchobs_NO_WS_CTL($$dpth + 1, $$cr)
  }
  public matchLF($$dpth: number, $$cr?: ErrorTracker): Nullable<LF> {
    return this.regexAccept(String.raw`(?:\x0A)`, '', $$dpth + 1, $$cr)
  }
  public matchCR($$dpth: number, $$cr?: ErrorTracker): Nullable<CR> {
    return this.regexAccept(String.raw`(?:\x0D)`, '', $$dpth + 1, $$cr)
  }
  public test(): boolean {
    const mrk = this.mark()
    const res = this.matchmailbox(0)
    const ans = res !== null
    this.reset(mrk)
    return ans
  }
  public parse(): ParseResult {
    const mrk = this.mark()
    const res = this.matchmailbox(0)
    if (res) return { ast: res, errs: [] }
    this.reset(mrk)
    const rec = new ErrorTracker()
    this.clearMemos()
    this.matchmailbox(0, rec)
    const err = rec.getErr()
    return { ast: res, errs: err !== null ? [err] : [] }
  }
  public mark(): PosInfo {
    return this.pos
  }
  // @ts-ignore: loopPlus may not be called
  private loopPlus<T>(func: $$RuleType<T>): Nullable<[T, ...T[]]> {
    return this.loop(func, 1, -1) as Nullable<[T, ...T[]]>
  }
  private loop<T>(func: $$RuleType<T>, lb: number, ub: number): Nullable<T[]> {
    const mrk = this.mark()
    const res: T[] = []
    while (ub === -1 || res.length < ub) {
      const preMrk = this.mark()
      const t = func()
      if (t === null || this.pos.overallPos === preMrk.overallPos) {
        break
      }
      res.push(t)
    }
    if (res.length >= lb) {
      return res
    }
    this.reset(mrk)
    return null
  }
  private run<T>($$dpth: number, fn: $$RuleType<T>): Nullable<T> {
    const mrk = this.mark()
    const res = fn()
    if (res !== null) return res
    this.reset(mrk)
    return null
  }
  // @ts-ignore: choice may not be called
  private choice<T>(fns: Array<$$RuleType<T>>): Nullable<T> {
    for (const f of fns) {
      const res = f()
      if (res !== null) {
        return res
      }
    }
    return null
  }
  private regexAccept(
    match: string,
    mods: string,
    dpth: number,
    cr?: ErrorTracker,
  ): Nullable<string> {
    return this.run<string>(dpth, () => {
      const reg = new RegExp(match, 'y' + mods)
      const mrk = this.mark()
      reg.lastIndex = mrk.overallPos
      const res = this.tryConsume(reg)
      if (cr) {
        cr.record(mrk, res, {
          kind: 'RegexMatch',
          // We substring from 3 to len - 1 to strip off the
          // non-capture group syntax added as a WebKit workaround
          literal: match.substring(3, match.length - 1),
          negated: this.negating,
        })
      }
      return res
    })
  }
  private tryConsume(reg: RegExp): Nullable<string> {
    const res = reg.exec(this.input)
    if (res) {
      let lineJmp = 0
      let lind = -1
      for (let i = 0; i < res[0].length; ++i) {
        if (res[0][i] === '\n') {
          ++lineJmp
          lind = i
        }
      }
      this.pos = {
        overallPos: reg.lastIndex,
        line: this.pos.line + lineJmp,
        offset:
          lind === -1
            ? this.pos.offset + res[0].length
            : res[0].length - lind - 1,
      }
      return res[0]
    }
    return null
  }
  // @ts-ignore: noConsume may not be called
  private noConsume<T>(fn: $$RuleType<T>): Nullable<T> {
    const mrk = this.mark()
    const res = fn()
    this.reset(mrk)
    return res
  }
  // @ts-ignore: negate may not be called
  private negate<T>(fn: $$RuleType<T>): Nullable<boolean> {
    const mrk = this.mark()
    const oneg = this.negating
    this.negating = !oneg
    const res = fn()
    this.negating = oneg
    this.reset(mrk)
    return res === null ? true : null
  }
  // @ts-ignore: Memoise may not be used
  private memoise<K>(
    rule: $$RuleType<K>,
    memo: Map<number, [Nullable<K>, PosInfo]>,
  ): Nullable<K> {
    const $scope$pos = this.mark()
    const $scope$memoRes = memo.get($scope$pos.overallPos)
    if (this.memoSafe && $scope$memoRes !== undefined) {
      this.reset($scope$memoRes[1])
      return $scope$memoRes[0]
    }
    const $scope$result = rule()
    if (this.memoSafe)
      memo.set($scope$pos.overallPos, [$scope$result, this.mark()])
    return $scope$result
  }
}
export function parse(s: string): ParseResult {
  const p = new Parser(s)
  return p.parse()
}
export interface ParseResult {
  ast: Nullable<mailbox>
  errs: SyntaxErr[]
}
export interface PosInfo {
  readonly overallPos: number
  readonly line: number
  readonly offset: number
}
export interface RegexMatch {
  readonly kind: 'RegexMatch'
  readonly negated: boolean
  readonly literal: string
}
export type EOFMatch = { kind: 'EOF'; negated: boolean }
export type MatchAttempt = RegexMatch | EOFMatch
export class SyntaxErr {
  public pos: PosInfo
  public expmatches: MatchAttempt[]
  constructor(pos: PosInfo, expmatches: MatchAttempt[]) {
    this.pos = pos
    this.expmatches = [...expmatches]
  }
  public toString(): string {
    return `Syntax Error at line ${this.pos.line}:${this.pos.offset}. Expected one of ${this.expmatches.map((x) => (x.kind === 'EOF' ? ' EOF' : ` ${x.negated ? 'not ' : ''}'${x.literal}'`))}`
  }
}
class ErrorTracker {
  private mxpos: PosInfo = { overallPos: -1, line: -1, offset: -1 }
  private regexset: Set<string> = new Set()
  private pmatches: MatchAttempt[] = []
  public record(pos: PosInfo, result: any, att: MatchAttempt) {
    if ((result === null) === att.negated) return
    if (pos.overallPos > this.mxpos.overallPos) {
      this.mxpos = pos
      this.pmatches = []
      this.regexset.clear()
    }
    if (this.mxpos.overallPos === pos.overallPos) {
      if (att.kind === 'RegexMatch') {
        if (!this.regexset.has(att.literal)) this.pmatches.push(att)
        this.regexset.add(att.literal)
      } else {
        this.pmatches.push(att)
      }
    }
  }
  public getErr(): SyntaxErr | null {
    if (this.mxpos.overallPos !== -1)
      return new SyntaxErr(this.mxpos, this.pmatches)
    return null
  }
}
